# Generated by Django 4.1.4 on 2022-12-12 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_profile_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image_url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
