# Generated by Django 4.1.4 on 2022-12-13 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_profile_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='image_url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='professionalaccomplishment',
            name='image_url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='image_url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
