# Generated by Django 4.1.4 on 2022-12-13 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_award_image_url_professionalaccomplishment_image_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='award',
            old_name='justification',
            new_name='photo',
        ),
        migrations.RenameField(
            model_name='professionalaccomplishment',
            old_name='justification',
            new_name='photo',
        ),
    ]
