# Generated by Django 4.1.4 on 2022-12-13 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_justification_award_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='pro_accomp/justifications'),
        ),
        migrations.AlterField(
            model_name='professionalaccomplishment',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='pro_accomp/justifications'),
        ),
    ]
