# Generated by Django 4.1.2 on 2022-12-13 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_award_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='pro_accomp/justifications'),
        ),
        migrations.AlterField(
            model_name='professionalaccomplishment',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='pro_accomp/justifications'),
        ),
    ]
