# Generated by Django 4.1.4 on 2022-12-13 19:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_award_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='pro_accomp/justifications'),
        ),
        migrations.AlterField(
            model_name='professionalaccomplishment',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='pro_accomp/justifications'),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_creation',
            field=models.DateField(default=datetime.date(2022, 1, 1)),
        ),
        migrations.AlterField(
            model_name='project',
            name='visual_demo',
            field=models.FileField(blank=True, null=True, upload_to='Project/demo'),
        ),
    ]
