# Generated by Django 4.1.4 on 2022-12-14 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_award_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='is_published',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
